Following suggestions, fixing error management and reimplementing lock.

diff --git a/src/recaplog b/src/recaplog
--- a/src/recaplog
+++ b/src/recaplog
@@ -33,7 +33,7 @@
 ## DEFAULT CONFIG ##
 PATH=/bin:/usr/bin:/sbin:/usr/sbin
 BASEDIR="/var/log/recap"
-LOCKFILE=/var/lock/recaplog.lock
+LOCKFILE="/var/lock/recaplog.lock"
 LOG_COMPRESS=1
 LOG_EXPIRY=0
 BACKUP_ITEMS="fdisk mysql netstat ps pstree resources"
@@ -60,24 +60,23 @@ log() {
   ## is helpful to avoid emails submitted, instead the logs contain the
   ## possible ERRORS
   if ! tty -s; then
-    echo "$( eval ts ) [${msg_type}] ${log_entry}" 2>&1 >> "${LOGFILE}"
+    echo "$( ts ) [${msg_type}] ${log_entry}" 2>&1 >> "${LOGFILE}"
     return 0
   fi
   if [[ "${VERBOSE}" ]]; then
-    echo "$( eval ts ) [${msg_type}] ${log_entry}" 2>&1 | tee -a "${LOGFILE}"
+    echo "$( ts ) [${msg_type}] ${log_entry}" 2>&1 | tee -a "${LOGFILE}"
     return 0
   fi
   if [[ "${msg_type}" =~ "ERROR" ||
         "${msg_type}" =~ "WARNING" ]]; then
-    echo "$( eval ts ) [${msg_type}] ${log_entry}" 2>&1 | tee -a "${LOGFILE}"
+    echo "$( ts ) [${msg_type}] ${log_entry}" 2>&1 | tee -a "${LOGFILE}"
   else
-    echo "$( eval ts ) [${msg_type}] ${log_entry}" 2>&1 >> "${LOGFILE}"
+    echo "$( ts ) [${msg_type}] ${log_entry}" 2>&1 >> "${LOGFILE}"
   fi
 }
 
 # Function to delete log files older than LOG_EXPIRY days
 delete_old_logs() {
-  local prefix_msg='Deleting:'
   local matched_files=''
   local empty_dirs=''
   local count_files=0
@@ -88,10 +87,7 @@ delete_old_logs() {
   fi
   # Proceed with deletion of old logs
   log INFO "Deleting log files older than ${LOG_EXPIRY} days..."
-  if [[ "${DRYRUN}" ]]; then
-    prefix_msg="Would delete:"
-  fi
-  # Deleting files and empty directories if any.
+  # Matching files and empty directories if any.
   # Using now posix-extended regex flavor to ease the matching of logs, gzips
   # or tarballs
   matched_files=$(
@@ -102,27 +98,31 @@ delete_old_logs() {
   if [[ -n "${matched_files}" ]]; then
     count_files=$( wc -l <<<"${matched_files}" )
   fi
-  log INFO "${prefix_msg} ${count_files} log files."
-  if [[ ! "${DRYRUN}" ]]; then
-    # Deleting old logs, compressed/tarballs and empty dirs if any
-    if [[ "${count_files}" -gt 0 ]]; then
-      while read matched_file; do
-        rm -f "${matched_file}"
-      done <<< "${matched_files}"
-    fi
-    # Deleting empty dirs generated by recaplog when no compressing logs.
-    empty_dirs=$( find "${BASEDIR}" -maxdepth 1 -regextype posix-extended \
-                    -regex "^${BASEDIR}/[a-z]+_[a-z]+_[0-9]{8}$" -empty \
-                    -type d )
-    if [[ -n "${empty_dirs}" ]]; then
-      count_dirs=$( wc -l <<<"${empty_dirs}" )
-    fi
-    log INFO "${prefix_msg} ${count_dirs} empty directories."
-    if [[ "${count_dirs}" -gt 0 ]]; then
-      while read emtpy_dir; do
-        rmdir "${emtpy_dir}"
-      done <<< "${empty_dirs}"
-    fi
+  # If dry run, log and return
+  if [[ "${DRYRUN}" ]]; then
+    log INFO "Would delete: ${count_files} log files."
+    return 0
+  else
+    log INFO "Deleting: ${count_files} log files."
+  fi
+  # Deleting old logs, compressed/tarballs and empty dirs if any
+  if [[ "${count_files}" -gt 0 ]]; then
+    while read matched_file; do
+      rm -f "${matched_file}"
+    done <<< "${matched_files}"
+  fi
+  # Deleting empty dirs generated by recaplog when no compressing logs.
+  empty_dirs=$( find "${BASEDIR}" -maxdepth 1 -regextype posix-extended \
+                  -regex "^${BASEDIR}/[a-z]+_[a-z]+_[0-9]{8}$" -empty \
+                  -type d )
+  if [[ -n "${empty_dirs}" ]]; then
+    count_dirs=$( wc -l <<<"${empty_dirs}" )
+  fi
+  log INFO "Deleting: ${count_dirs} empty directories."
+  if [[ "${count_dirs}" -gt 0 ]]; then
+    while read emtpy_dir; do
+      rmdir "${emtpy_dir}"
+    done <<< "${empty_dirs}"
   fi
 }
 
@@ -145,16 +145,14 @@ pack_old_logs() {
     YESTERDAY_ITEM_DIR="${BASEDIR}/${item}_daily_${YESTERDAYDATE}"
     err=''
     log INFO "Packing ${item}..."
-    log_count=$(
-      {
-        ls -1 "${BASEDIR}/${item}_${YESTERDAYDATE}"-*.log | wc -l
-      } 2>&1; exit ${PIPESTATUS[0]}
-    )
+    # Finding logs for item from yesterday date. 
+    output=$( ls -1 "${BASEDIR}/${item}_${YESTERDAYDATE}"-*.log 2>&1 )
     if [[ $? -ne 0 ]]; then
-      log ERROR "An error ocurred while reading logs: ${log_count}, "\
-                "skipping..."
+      output=$( tr -d '\n' <<< "${output}" )
+      log ERROR "An error ocurred while reading logs: '${output}', skipping..."
       continue
     fi
+    log_count=$( wc -l <<< "${output}" )
     # Moving logs to yesterday item's directory
     if [[ "${DRYRUN}" ]]; then
       log INFO "Would move ${log_count} logs to: ${YESTERDAY_ITEM_DIR}"
@@ -167,8 +165,9 @@ pack_old_logs() {
              "${YESTERDAY_ITEM_DIR}";
         } 2>&1
       )
+      err=$( tr -d '\n' <<< "${err}" )
       if [[ ! -z "${err}" ]]; then
-        log ERROR "An error ocurred while attempting to move logs ${err}, "\
+        log ERROR "An error ocurred while attempting to move logs: '${err}', "\
                   "skipping..."
         continue
       fi
@@ -192,33 +191,45 @@ pack_old_logs() {
         touch -t ${YESTERDAYDATE}0000 "${OUTPUTFILE}";
       } 2>&1
     )
+    err=$(tr -d '\n' <<< "${err}" )
     if [[ ! -z "${err}" ]]; then
-      log ERROR "An error ocurred while attempting to compress logs ${err}, "\
-                "skipping..."
+      log ERROR "An error ocurred while attempting to compress logs: '${err}'"\
+                ", skipping..."
       continue
     fi
     log INFO "Deleting ${log_count} logs."
     rm_err=$( { rm -Rf "${YESTERDAY_ITEM_DIR}"; } 2>&1 >/dev/null )
+    rm_err=$( tr -d '\n' <<< "${rm_err}" )
     if [[ ! -z "${rm_err}" ]]; then
-      log ERROR "An error ocurred while deleting logs ${rm_err}, skipping..."
-      continue
+      log ERROR "An error ocurred while deleting logs '${rm_err}', skipping..."
     fi
   done
 }
 
+# Cleanup function to remove lock
+cleanup() {
+  log INFO "$( basename $0 ) ($$): Caught exit signal - deleting ${LOCKFILE}"
+  rm -f "${LOCKFILE}"
+  exit 2
+}
+
 # Create a Lock so that recaplog does not try to run over itself.
 recaploglock() {
-  if mkdir "${LOCKFILE}"; then
-    # Remove LOCKFILE when the script finishes, or when it receives a signal
-    trap 'rm -rf "${LOCKFILE}"' 0  # remove directory when script finishes
-    trap "exit 2" 1 2 3 15         # terminate script when receiving signal
-  else
-    log ERROR "Cannot acquire lock, giving up on ${LOCKFILE}"
+  (set -C; echo "$$" > "${LOCKFILE}") 2>/dev/null
+  if [ $? -ne 0 ]; then
+    log ERROR "$( basename $0 ) ($$): Lock File exists - exiting"
     exit 1
+  else
+    trap 'cleanup' 1 2 15 17 19 23 EXIT
+    log INFO "$( basename $0 ) ($$): Created lock file: ${LOCKFILE}"
   fi
 }
 
-## MAIN ##
+
+# Avoid external variables to be defined
+unset VERBOSE
+unset DRYRUN
+
 while getopts hnv flag; do
   case ${flag} in
     n)
