Standardize options across scripts and update man pages

diff --git a/src/recap b/src/recap
--- a/src/recap
+++ b/src/recap
@@ -19,10 +19,10 @@
 #
 #~ Usage: _tool_ [OPTION]
 #~ Options:
-#~   -h,--help       Print this help.
-#~   -B,--backup     Copy the last log file to the backups dir.
-#~   -S,--snapshot   Take a timestamped snapshot outside the regular rotation.
-#~   -V,--version    Print version and exit.
+#~   -h, --help       Print this help.
+#~   -B, --backup     Copy the last log file to the backups dir.
+#~   -S, --snapshot   Take a timestamped snapshot outside the regular rotation.
+#~   -V, --version    Print version and exit.
 #~
 
 ## Version
@@ -32,7 +32,7 @@ declare -r _VERSION='1.4.0'
 declare -r DATE=$( date +%F_%T )
 declare -r LOCKFILE="/var/lock/recap.lock"
 declare -r LOG_SUFFIX=$( date +%Y%m%d-%H%M%S )
-declare -r LIBDIR="@LIBDIR@/recap"
+declare -r LIBDIR="/usr/local/lib/recap"
 declare -r COREDIR="${LIBDIR}/core"
 declare -r PLUGIN_A_DIR="${LIBDIR}/plugins-available"
 declare -r PLUGIN_E_DIR="${LIBDIR}/plugins-enabled"
@@ -479,15 +479,22 @@ check_disk_space() {
 
 ## Main
 
-# Evaluate input flags, print usage if more than one flag is used.
-if [[ "$#" -gt 1 ]]; then
- log ERROR "Error: Only one flag is allowed"
- print_usage
- exit 1
+# Set options
+OPTIONS=VBhS
+LONG_OPTIONS=version,backup,help,snapshot
+
+# Parse options and show usage if invalid options provided
+! ALL_ARGS=$(getopt --options=${OPTIONS} --longoptions=${LONG_OPTIONS} --name "$0" -- "$@")
+if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
+  print_usage
+  exit 1
 fi
 
-# If we only have one flag, see if we know how to handle it.
-if [[ "$#" -gt 0 ]]; then
+# Set the positional parameters to the parsed options
+set -- ${ALL_ARGS}
+
+# Act on the valid arguments provided
+while true; do
   case "$1" in
     -V|--version)
       echo "${_VERSION}"
@@ -496,6 +503,7 @@ if [[ "$#" -gt 0 ]]; then
     -B|--backup)
       # backup latest log files
       BACKUP="yes"
+      shift
       ;;
     -h|--help)
       # print usage
@@ -505,13 +513,29 @@ if [[ "$#" -gt 0 ]]; then
     -S|--snapshot)
       # take a snapshot outside of the regular output rotation
       SNAPSHOT="yes"
+      shift
       ;;
+    --)
+      shift; break ;;
     *)
       # user entered an invalid flag, print warning and exit
       log ERROR "Invalid Input"
       print_usage
       exit 1
   esac
+done
+
+if [[ "${BACKUP,,}" == "yes" && "${SNAPSHOT,,}" == "yes" ]]; then
+  log ERROR "Backup and Snapshot options are mutually exclusive"
+  print_usage
+  exit 1
+fi
+
+# Error if unparsed arguments exist
+if [[ "$#" -gt 0 ]]; then
+  log ERROR "Error: Unexpected argument(s): $@"
+  print_usage
+  exit 1
 fi
 
 # Verify that script is being run as root
diff --git a/src/recaptool b/src/recaptool
--- a/src/recaptool
+++ b/src/recaptool
@@ -17,14 +17,17 @@
 #   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 #
 #
-#~ Usage: _tool_ [OPTIONS]
+#~ Usage: _tool_ OPTIONS
 #~ Options:
-#~   {proc|mem|memproc} PROCESS_NAME  Show proc/mem info of PROCESS_NAME.
-#~   {net|netestab} PORT              Show network connections of a PORT.
-#~   querycount                       Show mysql connections.
-#~   -d PATH                          Specify the recap log PATH.
-#~   -h,--help                        Print this help.
-#~   -V,--version                     Print version and exit.
+#~   -c, --connections PORT           Show all network connections of a PORT.
+#~   -e, --established PORT           Show only established network connections of a PORT.
+#~   -d, --path PATH                  Specify the recap log PATH.
+#~   -m, --mem  PROCESS_NAME          Show mem info of PROCESS_NAME.
+#~   -p, --proc PROCESS_NAME          Show proc info of PROCESS_NAME.
+#~   -b, --memproc PROCESS_NAME       Show both mem and proc info of PROCESS_NAME.
+#~   -q, --querycount                 Show mysql connections.
+#~   -h, --help                       Print this help.
+#~   -V, --version                    Print version and exit.
 #~
 
 ## Version
@@ -41,127 +44,172 @@ if [[ -r "${CONFFILE}" ]]; then
 fi
 
 memproc() {
-	PROCESS="${1}"
-	TMP=$( mktemp )
-	>"${TMP}"
-	for i in $( ls "${BASEDIR}"/ps_*.log ); do
-		head -n 1 "${i}" | tr "\n" "\t" >> "${TMP}"
-		egrep "${PROCESS}" "${i}" -c | tr "\n" "\t" >> "${TMP}"
-		egrep "${PROCESS}" "${i}" | awk '{ SUM += $6 } END {print SUM/1024, "M"};' >> "${TMP}"
-	done
-	sort "${TMP}"
-	rm -f "${TMP}"
+  set -x
+  PROCESS="${@}"
+  TMP=$( mktemp )
+  >"${TMP}"
+  for i in $( ls "${BASEDIR}"/ps_*.log ); do
+    head -n 1 "${i}" | tr "\n" "\t" >> "${TMP}"
+    egrep "${PROCESS}" "${i}" -c | tr "\n" "\t" >> "${TMP}"
+    egrep "${PROCESS}" "${i}" | awk '{ SUM += $6 } END {print SUM/1024, "M"};' >> "${TMP}"
+  done
+  sort "${TMP}"
+  rm -f "${TMP}"
+  set +x
 }
 
 proc() {
-	PROCESS="${1}"
-	TMP=$( mktemp )
-	>"${TMP}"
-	for i in $( ls "${BASEDIR}"/ps_*.log ); do
-		head -n 1 "${i}" | tr "\n" "\t" >> "${TMP}"
-		egrep "${PROCESS}" "${i}" -c >> "${TMP}"
-	done
-	sort "${TMP}"
-	rm -f "${TMP}"
+  PROCESS="${@}"
+  TMP=$( mktemp )
+  >"${TMP}"
+  for i in $( ls "${BASEDIR}"/ps_*.log ); do
+    head -n 1 "${i}" | tr "\n" "\t" >> "${TMP}"
+    egrep "${PROCESS}" "${i}" -c >> "${TMP}"
+  done
+  sort "${TMP}"
+  rm -f "${TMP}"
 }
 
 mem() {
-	PROCESS="${1}"
-	TMP=$( mktemp )
-	>"${TMP}"
-	for i in $( ls "${BASEDIR}"/ps_*.log ); do
-		head -n 1 "${i}" | tr "\n" "\t" >> "${TMP}"
-		egrep "${PROCESS}" "${i}" | awk '{ SUM += $6 } END {print SUM/1024, "M"};' >> "${TMP}"
-	done
-	sort "${TMP}"
-	rm -f "${TMP}"
+  PROCESS="${@}"
+  TMP=$( mktemp )
+  >"${TMP}"
+  for i in $( ls "${BASEDIR}"/ps_*.log ); do
+    head -n 1 "${i}" | tr "\n" "\t" >> "${TMP}"
+    egrep "${PROCESS}" "${i}" | awk '{ SUM += $6 } END {print SUM/1024, "M"};' >> "${TMP}"
+  done
+  sort "${TMP}"
+  rm -f "${TMP}"
 }
 
-net() {
-	PORT="${1}"
-	TMP=$( mktemp )
-	>"${TMP}"
-	for i in $( ls "${BASEDIR}"/netstat_*.log ); do
-		head -n 1 "${i}" | tr "\n" "\t" >> "${TMP}"
-		egrep -c ":${PORT} " "${i}" >> "${TMP}"
-	done
-	sort "${TMP}"
-	rm -f "${TMP}"
+connections() {
+  PORT="${@}"
+  TMP=$( mktemp )
+  >"${TMP}"
+  for i in $( ls "${BASEDIR}"/netstat_*.log ); do
+    head -n 1 "${i}" | tr "\n" "\t" >> "${TMP}"
+    egrep -c ":${PORT} " "${i}" >> "${TMP}"
+  done
+  sort "${TMP}"
+  rm -f "${TMP}"
 }
 
-netestab() {
-	PORT="${1}"
-	TMP=$( mktemp )
-	>"${TMP}"
-	for i in $( ls "${BASEDIR}"/netstat_*.log ); do
-		head -n 1 "${i}" | tr "\n" "\t" >> "${TMP}"
-		egrep -c "ESTAB .*:${PORT} " "${i}" >> "${TMP}"
-	done
-	sort "${TMP}"
-	rm -f "${TMP}"
+established() {
+  PORT="${@}"
+  TMP=$( mktemp )
+  >"${TMP}"
+  for i in $( ls "${BASEDIR}"/netstat_*.log ); do
+    head -n 1 "${i}" | tr "\n" "\t" >> "${TMP}"
+    egrep -c "ESTAB .*:${PORT} " "${i}" >> "${TMP}"
+  done
+  sort "${TMP}"
+  rm -f "${TMP}"
 }
 
 querycount() {
-	TMP=$( mktemp )
-	>"${TMP}"
-	for i in $( ls "${BASEDIR}"/mysql_*.log ); do
-		head -n 1 "${i}" | tr "\n" "\t" >> "${TMP}"
-		grep "Query" -c "${i}" >> "${TMP}"
-	done
-	sort "${TMP}"
-	rm -f "${TMP}"
+  TMP=$( mktemp )
+  >"${TMP}"
+  for i in $( ls "${BASEDIR}"/mysql_*.log ); do
+    head -n 1 "${i}" | tr "\n" "\t" >> "${TMP}"
+    grep "Query" -c "${i}" >> "${TMP}"
+  done
+  sort "${TMP}"
+  rm -f "${TMP}"
 }
 
 print_usage() {
+  echo
   grep -E '^#~' "${0}" | sed -e 's/^#~\s\?//' \
                              -e "s/_tool_/$( basename ${0} )/"
 }
 
-if [[ ${#} -eq 0 ]]; then
-  echo "Error: No arguments provided."
-	print_usage
-	exit 1
+# Set options
+OPTIONS=Vc:d:e:m:p:b:qh
+LONG_OPTIONS=version,connections:,path:,established:,mem:,proc:,memproc:,querycount,help
+
+# Parse options and show usage if invalid options provided
+! ALL_ARGS=$(getopt --options=${OPTIONS} --longoptions=${LONG_OPTIONS} --name "$0" -- "$@")
+if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
+  print_usage
+  exit 1
 fi
 
+# Set the positional parameters to the parsed options
+eval set -- "${ALL_ARGS}"
+
+# Create an array to store commands to be executed
+declare -a CMDS
+
+# Act on the valid arguments provided
 while [[ ${#} -gt 0 ]]; do
-	case "${1}" in
+  case "${1}" in
     -V|--version)
       echo "${_VERSION}"
       exit 0
       ;;
-		-d)
-			if [[ -d "${2}" ]]; then
-				BASEDIR="${2}"
-				shift 2
-			else
-				echo "Error: ${2} is not a valid directory."
-				print_usage
-				exit 1
-			fi
-			;;
+    -c|--connections)
+        PORT=${2}
+        shift 2
+        CMDS+=("connections ${PORT}")
+      ;;
+    -e|--established)
+        PORT=${2}
+        shift 2
+        CMDS+=("established ${PORT}")
+      ;;
+    -d|--path)
+      DIR=true
+      if [[ -d "${2}" ]]; then
+        BASEDIR="${2}"
+        shift 2
+      else
+        echo "Error: ${2} is not a valid directory."
+        print_usage
+        exit 1
+      fi
+      ;;
+    -m|--mem)
+        PROCESS_NAME="${2}"
+        shift 2
+        CMDS+=("mem ${PROCESS_NAME}")
+      ;;
+    -p|--proc)
+        PROCESS_NAME="${2}"
+        shift 2
+        CMDS+=("proc ${PROCESS_NAME}")
+      ;;
+    -b|--memproc)
+        PROCESS_NAME="${2}"
+        shift 2
+        CMDS+=("memproc ${PROCESS_NAME}")
+      ;;
+    -q|--querycount)
+        CMDS+=(querycount)
+        shift
+      ;;
     -h|--help)
         print_usage
         exit 0
       ;;
-		memproc|proc|mem|net|netestab)
-			cmds="${cmds}${1} ${2} "
-			shift 2
-			;;
-		querycount)
-			cmds="${cmds}${1} "
-			shift
-			;;
-		*)
-			echo "Error: Invalid command ${1}"
-			print_usage
-			exit 1
-			;;
-	esac
+    --)
+      shift; break ;;
+  esac
 done
 
-echo "Information: Using ${BASEDIR} as recap log path"
-echo "Information: Executing ${cmds}"
+if [[ ${#CMDS[@]} -eq 0 ]]; then
+  msg="Error: Please supply more arguments."
+  [[ $DIR ]] && msg="${msg} The 'path' option is not enough."
+  echo "${msg}"
+  print_usage
+  exit 1
+fi
 
-${cmds}
+echo "Information: Using ${BASEDIR} as recap log path"
+
+for cmd in "${CMDS[@]}"; do
+  echo "Information: Executing ${cmd}"
+  eval ${cmd}
+  echo
+done
 
 exit 0
